I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_zero.rpy", line 200, in script
    sue "Roar"
Exception: Sayer 'sue' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_zero.rpy", line 200, in script
    sue "Roar"
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Hart\Downloads\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'sue' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.1.23060707
DIAR Day 0 Prototype 1.0
Sun Jul 30 08:31:23 2023
